### ISSUE TITLE
Data set can not be downloaded

### ISSUE THREAD

**Issue by MrLihj** [shinianzhihou/ChangeDetection#5]
I found that it posed a problem of 404, when I clicked your provided link, Can you give another?

**Comment by DwRolin** [comment]
http://web.eee.sztaki.hu/remotesensing/airchange_benchmark.html
account name：sztaki   password：deva

**Comment by AngieNikki** [comment]
I have some questions about the data storage format. I am new to deep learning and I dont know how the "train.csv & test.csv" files are written. Could you share your .csv file or show a screenshot of your .csv file or give me some suggestions?

**Comment by DwRolin** [comment]
I am also new to deep learning.I don't use the code in the blog,&nbsp; it's difficult for me to understand the disposition of train data. I reference this blog.I attach my codes with mail.
https://github.com/kyoukuntaro/FCSN_for_ChangeDetection_IGARSS2018
I don't use&nbsp; modular design,the main codes are train.py and make_dataset.py.I use&nbsp;SZTAKI instead of OSCD dataset.To expand dataset,I use some data augument(brightness,contrast,color,sharp,flip horizontal,flip vertical).And&nbsp; cutting image pair with 224*224 size randomly,making sure the change pixels accounted for 1% of total pixels,putting img1,img2,label data in 7 dimensional numpy. Every image pair is divided into 50 mini image-data.
The rest of code is simple.I have trained&nbsp; FC-siam-conv and FC-siam-diff successfully.Attaching two pictures about training process.
If you use my codes in trial training,be careful to folder name.
Hope the mail will be helpful.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AngieNikki"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 中午12:23
收件人:&nbsp;"shinianzhihou/ChangeDetection"<ChangeDetection@noreply.github.com&gt;;
抄送:&nbsp;"1321125854"<1321125854@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [shinianzhihou/ChangeDetection] Data set can not be downloaded (#5)





 
I have some questions about the data storage format. I am new to deep learning and I dont know how the "train.csv &amp; test.csv" files are written. Could you share your .csv file or show a screenshot of your .csv file or give me some suggestions?

**Comment by shinianzhihou** [comment]
I'm sorry to reply to you so late! (Be very busy with my graduation project... )

1. How to divide the images to Dataset ? 
I have upload the `tools.ipynb` , maybe you can find something useful in the part "datamaker" of the notebook and the scripts `utils/datamaker.py`.

2. How to get the raw images? (thanks to @DwRolin )
```
http://web.eee.sztaki.hu/remotesensing/airchange_benchmark.html
account name：sztaki password：deva
```
(But you should do `Histogram correction` on the images. The code for `Histogram correction` is easy to get in Google, and I will upload my code when i am back to my laboratory.)

3. train.csv or test.csv?
You can get them by balabala (the first question)
(test.csv)
![image](https://user-images.githubusercontent.com/29772895/80340810-e9a9a280-8893-11ea-85d8-f6c24ad36549.png)
(train.csv)
![image](https://user-images.githubusercontent.com/29772895/80340880-03e38080-8894-11ea-8a6d-1fe2a7e091cc.png)

**Comment by AngieNikki** [comment]
Thank all of you guys very much for your help！！

**Comment by songyiren98** [comment]
Thank you, I have run your code successfully, how can I test my model, I mean where to find the output image?

**Comment by shinianzhihou** [comment]
![image](https://user-images.githubusercontent.com/29772895/83960077-1ef3d800-a8b7-11ea-8997-d714adca4166.png)

**Comment by ghost** [comment]
checkpoint 失效了，可以发一下吗

**Comment by zmxhhh** [comment]
> Thank you, I have run your code successfully, how can I test my model, I mean where to find the output image?

Hello, could you please send me a pre-training model? If possible, my email address is 2587423208@qq.com. Thank you very much.

**Comment by xqqelove** [comment]
Excuse me, what does P_change mean in the .csv files? And how to calculate it?

**Comment by shinianzhihou** [comment]
> Excuse me, what does P_change mean in the .csv files? And how to calculate it?

P_change means the percentage of pixels that change in an image.
for example, if 60 pixels of 100 pixels have changed, then p_change is 0.6

**Comment by shinianzhihou** [comment]
A totally NEW repo is released, for which I have closed this good first issue! THANKS EVERYONE!
